apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - serviceaccounts.yaml
  - secrets.yaml
  - ollama-service.yaml
  - ollama-statefulset.yaml
  - litellm-configmap.yaml
  - litellm-postgres.yaml
  - litellm-service.yaml
  - litellm-deployment.yaml
  - openwebui-service.yaml
  - openwebui-deployment.yaml
  - model-pull-job.yaml
  - ingress.yaml
