apiVersion: v1
kind: Service
metadata:
  name: openwebui
  namespace: ai-dev
  labels:
    app.kubernetes.io/name: openwebui
spec:
  selector:
    app.kubernetes.io/name: openwebui
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
