apiVersion: v1
kind: Secret
metadata:
  name: ai-secrets
  namespace: ai-dev
type: Opaque
stringData:
  # Remplacer en production
  LITELLM_MASTER_KEY: "sk-dev-change-me-very-strong"
  WEBUI_SECRET_KEY: "webui-dev-change-me-very-strong"
  LITELLM_POSTGRES_PASSWORD: "litellm-dev-change-me-strong"
  LITELLM_DATABASE_URL: "postgresql://litellm:litellm-dev-change-me-strong@litellm-postgres.ai-dev.svc.cluster.local:5432/litellm"
