apiVersion: v1
kind: ServiceAccount
metadata:
  name: ollama
  namespace: ai-dev
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: litellm
  namespace: ai-dev
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openwebui
  namespace: ai-dev
automountServiceAccountToken: false
