apiVersion: v1
kind: Service
metadata:
  name: apm-server
  labels:
    app.kubernetes.io/name: apm-server
spec:
  selector:
    app.kubernetes.io/name: apm-server
  ports:
    - name: http
      port: 8200
      targetPort: 8200
      protocol: TCP
