apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - filebeat-rbac.yaml
  - filebeat-configmap.yaml
  - filebeat-daemonset.yaml
  - metricbeat-rbac.yaml
  - metricbeat-configmap.yaml
  - metricbeat-daemonset.yaml
  - networkpolicy-default-deny-ingress.yaml
  - networkpolicy-allow-beats-egress.yaml
