apiVersion: v1
kind: Service
metadata:
  name: ai-saas-portal
  namespace: ai-saas-dev
spec:
  selector:
    app.kubernetes.io/name: ai-saas-portal
  ports:
    - name: http
      port: 80
      targetPort: 8080
