apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-saas-frontend
  namespace: ai-saas-dev
  labels:
    app.kubernetes.io/name: ai-saas-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ai-saas-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ai-saas-frontend
    spec:
      automountServiceAccountToken: false
      containers:
        - name: ai-saas-frontend
          image: ai-saas-frontend:dev-local
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 8
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
