apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-saas-portal
  namespace: ai-saas-dev
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: traefik
  rules:
    - host: ai-portal-dev.79.137.32.27.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-saas-portal
                port:
                  number: 80
