apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ai-saas-portal
  namespace: ai-saas-dev
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - ai-portal-dev.79.137.32.27.nip.io
      secretName: ai-portal-dev-tls
  rules:
    - host: ai-portal-dev.79.137.32.27.nip.io
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: ai-saas-portal
                port:
                  number: 80
          - path: /checkout/manual
            pathType: Prefix
            backend:
              service:
                name: ai-saas-portal
                port:
                  number: 80
          - path: /checkout/mock
            pathType: Prefix
            backend:
              service:
                name: ai-saas-portal
                port:
                  number: 80
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: ai-saas-portal
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ai-saas-frontend
                port:
                  number: 80
