apiVersion: v1
kind: Secret
metadata:
  name: ai-saas-secrets
  namespace: ai-saas-dev
type: Opaque
stringData:
  POSTGRES_DB: ai_saas
  POSTGRES_USER: ai_saas
  POSTGRES_PASSWORD: ai_saas_change_me
  DATABASE_URL: postgresql+psycopg2://ai_saas:ai_saas_change_me@ai-saas-postgres:5432/ai_saas
  JWT_SECRET: change-this-jwt-secret
  PAYMENT_WEBHOOK_SECRET: change-this-webhook-secret
  LITELLM_MASTER_KEY: change-this-litellm-master-key
