apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-wallet-keycloak
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: keycloak
          resources:
            requests:
              cpu: 500m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 2Gi
