apiVersion: apps/v1
kind: Deployment
metadata:
  name: social-wallet-keycloak
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: keycloak
          resources:
            requests:
              cpu: "1"
              memory: 2Gi
            limits:
              cpu: "3"
              memory: 3Gi
