apiVersion: v1
kind: Service
metadata:
  name: social-wallet-postgres
  labels:
    app.kubernetes.io/name: social-wallet-postgres
spec:
  selector:
    app.kubernetes.io/name: social-wallet-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
