apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - ../../base

patches:
  - path: patch-kibana-ingress.yaml
  - path: patch-elasticsearch-resources.yaml
